#!/bin/bash
sqlplus -s "/ as sysdba" << EOF
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER ${DB_USER} IDENTIFIED BY "${DB_PASSWORD}" CONTAINER=ALL;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO ${DB_USER};
EXIT;
EOF
