-- 1. 시퀀스 생성 (INCREMENT BY = JPA allocationSize = 50)
CREATE SEQUENCE SEQ_USERS           START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEETINGS        START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CANDIDATE_SLOTS START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PARTICIPANTS    START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AVAILABILITIES  START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

-- 2. IDENTITY 속성 제거
ALTER TABLE users           MODIFY id DROP IDENTITY;
ALTER TABLE meetings        MODIFY id DROP IDENTITY;
ALTER TABLE candidate_slots MODIFY id DROP IDENTITY;
ALTER TABLE participants    MODIFY id DROP IDENTITY;
ALTER TABLE availabilities  MODIFY id DROP IDENTITY;

-- 3. 시퀀스를 DEFAULT로 지정
ALTER TABLE users           MODIFY id DEFAULT SEQ_USERS.NEXTVAL NOT NULL;
ALTER TABLE meetings        MODIFY id DEFAULT SEQ_MEETINGS.NEXTVAL NOT NULL;
ALTER TABLE candidate_slots MODIFY id DEFAULT SEQ_CANDIDATE_SLOTS.NEXTVAL NOT NULL;
ALTER TABLE participants    MODIFY id DEFAULT SEQ_PARTICIPANTS.NEXTVAL NOT NULL;
ALTER TABLE availabilities  MODIFY id DEFAULT SEQ_AVAILABILITIES.NEXTVAL NOT NULL;
