-- 기존 guest_token 관련 제약 제거
ALTER TABLE PARTICIPANTS DROP CONSTRAINT chk_participant_identity;
ALTER TABLE PARTICIPANTS DROP CONSTRAINT uq_participant_guest;
ALTER TABLE PARTICIPANTS DROP COLUMN guest_token;

-- PIN 인증 컬럼 추가
ALTER TABLE PARTICIPANTS ADD pin_hash VARCHAR2(255);
ALTER TABLE PARTICIPANTS ADD pin_fail_count NUMBER(3) DEFAULT 0 NOT NULL;
ALTER TABLE PARTICIPANTS ADD pin_locked_until TIMESTAMP;